//! Cache and Temporary File Cleaning Module
//!
//! This module provides safe cleaning of system caches, logs, and temporary files.
//! All operations support dry-run mode for safety.
//!
//! **Focus**: AI agent artifact cleanup with recovery system
//!
//! This module specializes in cleaning artifacts generated by AI agents:
//! - Git repositories and pack files
//! - AI agent caches (Cursor, GitHub Copilot, Claude, etc.)
//! - Xcode derived data and archives
//! - Homebrew cache files
//! - Time Machine snapshots
//!
//! All cleanup operations use a recovery-first approach where files are archived
//! before deletion, allowing restoration if needed.

#![warn(
    missing_docs,
    missing_debug_implementations,
    missing_copy_implementations
)]

pub mod ai_artifacts;
pub mod cleaner;
pub mod recovery;
pub mod targets;
pub mod time_machine;

pub use ai_artifacts::{AIArtifactCleaner, AIArtifactLocations};
pub use cleaner::SystemCleaner;
pub use recovery::{RecoveryItem, RecoveryManager, RecoveryManifest};
pub use targets::CleanTarget;
pub use time_machine::{Snapshot, TimeMachineManager};

/// Module version
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
